
# src/utils/__init__.py
# Project: Deep Learning IDS Using LSTM
# Developer: Kayode Timileyin Nicholas
# Purpose: Marks src/utils/ as a Python package and exposes
#          the most frequently imported symbols so callers
#          can write:
#              from src.utils import get_logger, set_global_seed
#          instead of reaching into individual sub-modules.

from src.utils.constants import (
    RANDOM_SEED,
    NSL_KDD_COLUMNS,
    NSL_KDD_CATEGORICAL_FEATURES,
    NSL_KDD_NUMERICAL_FEATURES,
    NSL_KDD_TARGET_COLUMN,
    NSL_KDD_ATTACK_TO_CATEGORY,
    NSL_KDD_CATEGORY_TO_INT,
    NSL_KDD_INT_TO_CATEGORY,
    NSL_KDD_CLASS_NAMES,
    NSL_KDD_NUM_CLASSES,
    NSL_KDD_NUM_FEATURES,
    DEFAULT_WINDOW_SIZE,
    DEFAULT_STEP_SIZE,
    TRAIN_RATIO,
    VAL_RATIO,
    TEST_RATIO,
    SUPPORTED_DATASETS,
    SUPPORTED_MODELS,
)

from src.utils.logger import (
    get_logger,
    get_pipeline_logger,
    get_training_logger,
    set_global_log_level,
    log_section_header,
    log_dict,
)

from src.utils.paths import (
    PROJECT_ROOT,
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    FIGURES_DIR,
    TABLES_DIR,
    METRICS_DIR,
    LOGS_DIR,
    FINAL_MODEL_DIR,
    CHECKPOINTS_DIR,
    BASELINES_DIR,
    PREDICTIONS_DIR,
    create_project_directories,
    ensure_dir,
    get_raw_data_dir,
    assert_file_exists,
)

from src.utils.helpers import (
    set_global_seed,
    Timer,
    format_duration,
    compute_class_distribution,
    compute_class_weights,
    summarise_dataset,
    flatten_sequences,
    one_hot_to_labels,
    labels_to_one_hot,
    save_json,
    load_json,
    format_metrics_table,
    get_timestamp,
    print_banner,
    validate_array_shapes,
    check_label_consistency,
)

from src.utils.serialization import (
    save_keras_model,
    load_keras_model,
    save_object,
    load_object,
    save_numpy_array,
    load_numpy_array,
    save_processed_arrays,
    load_processed_arrays,
    save_metadata,
    load_metadata,
    save_feature_names,
    load_feature_names,
    save_preprocessing_artifacts,
    load_preprocessing_artifacts,
    save_baseline_model,
    load_baseline_model,
    save_baseline_results,
)

__all__ = [
    # constants
    "RANDOM_SEED",
    "NSL_KDD_COLUMNS",
    "NSL_KDD_CATEGORICAL_FEATURES",
    "NSL_KDD_NUMERICAL_FEATURES",
    "NSL_KDD_TARGET_COLUMN",
    "NSL_KDD_ATTACK_TO_CATEGORY",
    "NSL_KDD_CATEGORY_TO_INT",
    "NSL_KDD_INT_TO_CATEGORY",
    "NSL_KDD_CLASS_NAMES",
    "NSL_KDD_NUM_CLASSES",
    "NSL_KDD_NUM_FEATURES",
    "DEFAULT_WINDOW_SIZE",
    "DEFAULT_STEP_SIZE",
    "TRAIN_RATIO",
    "VAL_RATIO",
    "TEST_RATIO",
    "SUPPORTED_DATASETS",
    "SUPPORTED_MODELS",
    # logger
    "get_logger",
    "get_pipeline_logger",
    "get_training_logger",
    "set_global_log_level",
    "log_section_header",
    "log_dict",
    # paths
    "PROJECT_ROOT",
    "DATA_DIR",
    "RAW_DATA_DIR",
    "PROCESSED_DATA_DIR",
    "FIGURES_DIR",
    "TABLES_DIR",
    "METRICS_DIR",
    "LOGS_DIR",
    "FINAL_MODEL_DIR",
    "CHECKPOINTS_DIR",
    "BASELINES_DIR",
    "PREDICTIONS_DIR",
    "create_project_directories",
    "ensure_dir",
    "get_raw_data_dir",
    "assert_file_exists",
    # helpers
    "set_global_seed",
    "Timer",
    "format_duration",
    "compute_class_distribution",
    "compute_class_weights",
    "summarise_dataset",
    "flatten_sequences",
    "one_hot_to_labels",
    "labels_to_one_hot",
    "save_json",
    "load_json",
    "format_metrics_table",
    "get_timestamp",
    "print_banner",
    "validate_array_shapes",
    "check_label_consistency",
    # serialization
    "save_keras_model",
    "load_keras_model",
    "save_object",
    "load_object",
    "save_numpy_array",
    "load_numpy_array",
    "save_processed_arrays",
    "load_processed_arrays",
    "save_metadata",
    "load_metadata",
    "save_feature_names",
    "load_feature_names",
    "save_preprocessing_artifacts",
    "load_preprocessing_artifacts",
    "save_baseline_model",
    "load_baseline_model",
    "save_baseline_results",
]